core/urls.py
from django.urls import path

from . import views

app_name = 'core'

urlpatterns = [
    # Website base index views urls
    # home page url
    path('', views.BaseIndexView.as_view(), name="base-index"),
    # wish create, update, detail, delete, list views' urls
    path('wish/create/', views.WishCreateView.as_view(), name="create-wish"),
    path('wish/update/<slug:slug>', views.WishUpdateView.as_view(), name="update-wish"),
    # path('wish/detail/<str:slug>', views.WishDetailView.as_view(), name="detail-wish"),
    path('<slug:slug>', views.WishDetailView.as_view(), name="detail-wish"),
    path('wish/delete/', views.WishDeleteView.as_view(), name="delete-wish"),
    path('wishes/', views.WishesListView.as_view(), name="wishes"),
    # ajax views' urls
    path('wishes-ajax/', views.WishAjaxView.as_view(), name="wishes-ajax"),
    path('subscribe/', views.SubscribeView.as_view(), name="subscribe"),
    # additional pages' urls
    path('coming-soon/', views.ComingSoonView.as_view(), name="coming-soon"),
    path('privacy-policy/', views.PrivacyPolicyView.as_view(), name="privacy-policy"),
    path('howitworks/', views.HowItWorksView.as_view(), name="howitworks"),
]

wishX/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
# if you have multilang website uncomment
from django.conf.urls.static import static
from core.consumers import *
from django.conf.urls.i18n import i18n_patterns  # for url translation

# from oscar.app import application # oscar applications urls here


urlpatterns = [
    path('jet/', include('jet.urls', 'jet')),
    path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
    path('labmin/', admin.site.urls),
    path('auth/', include('social_django.urls', namespace='social')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

websocket_urlpatterns = [
    path('comment/<slug:slug>', CommentConsumer, name='donation-comment'),
    path('like/<slug:slug>', LikeDislikeConsumer, name='like-dislike'),
]

urlpatterns += i18n_patterns(
    path('', include("core.urls", namespace='core')),
    path('page/', include('django.contrib.flatpages.urls')),
    path('accounts/', include('base_user.urls', namespace='account')),
)

urlpatterns += websocket_urlpatterns

if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += [
        path('translation/', include('rosetta.urls'))
    ]

# handler404 = 'game.views.NotFoundPage.as_view'

# in development django built-in server serves static and media content
if not settings.PROD:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# This is change default admin panel Headers and titles
admin.site.site_header = 'Wishx Admin'
admin.site.site_title = 'Wishx Administration'
admin.site.index_title = 'Wishx Administration'

core/forms.py
from django import forms
from core.models import *
from django.utils.translation import ugettext_lazy as _
from core.options.tools import CURRENCY


# Your forms here

class WishCreationForm(forms.ModelForm):
    """
    Form for creation wish
    """
    multi_image = forms.FileField(required=False,
        widget=forms.ClearableFileInput(
            attrs={'class': 'd-none',
                   'multiple': True,
                   'accept': 'image/jpeg, image/png',
                   'id': 'event-photo-input',
                   }
        )
    )
    currency = forms.ChoiceField(
        choices=CURRENCY,
        widget=forms.RadioSelect(attrs={'class': 'option-input radio mr-1'}),
        required=True)

    class Meta:
        model = Wish
        fields = (
            'name',
            'surname',
            'title',
            'description',
            'image',
            'required_amount',
            'currency',
            'video',
            # 'published',
            'slug',
            'identification_card_image',
        )

        widgets = {
            'image': forms.FileInput(
                attrs={'class': 'd-none',
                       'id': 'person-photo-input',
                       'accept': 'image/jpeg, image/png'}
            ),
            'identification_card_image': forms.FileInput(
                attrs={'class': 'd-none',
                       'accept': 'image/jpeg, image/png',
                       'id': 'identification-card-input',
                       }
            ),
            'name': forms.TextInput(
                attrs={'class': 'form-input w-100',
                       'id': 'person-name',
                       'placeholder': _('Ad')}
            ),
            'surname': forms.TextInput(
                attrs={'class': 'form-input w-100',
                       'id': 'person-surname',
                       'placeholder': _('Soyad')}
            ),
            'title': forms.TextInput(
                attrs={'class': 'form-input w-100',
                       'id': 'event-name',
                       'placeholder': _('Tədbirin adı')}
            ),
            'slug': forms.TextInput(
                attrs={'class': 'form-input w-100',
                       'id': 'event-shorname',
                       'placeholder': _('Məsələn: menimarzum')}
            ),
            'description': forms.Textarea(
                attrs={'class': 'form-input w-100 textarea pt-4',
                       'id': 'event-desc',
                       'rows': '12'}
            ),
            'required_amount': forms.NumberInput(
                attrs={'class': 'form-input col-7 mr-auto',
                       'id': 'required-amount',
                       'min': '0'}
            ),
            'video': forms.TextInput(
                attrs={'class': 'form-input w-100',
                       'id': 'event-video-input',
                       'placeholder': _('Video yüklə')}
            )
        }

        error_messages = {
            'slug': {
                'unique': _('This short link is already exists')
            },
            'identification_card_image': {
                'required': _('No file selected')
            }
        }


class WishUpdateForm(WishCreationForm):
    pass


class DonationCommentForm(forms.ModelForm):
    class Meta:
        model = Reply
        fields = (
            'comment',
        )
        widgets = {
            'comment': forms.Textarea(
                attrs={'class': 'reply__text p-2 px-sm-3 px-md-4 mr-2',
                       'id': 'reply-text',
                       'placeholder': _('Write a reply...'),
                       'rows': '2'
                       }
            ),
        }


class SubscribeForm(forms.ModelForm):
    class Meta:
        model = Subscribers
        fields = ("email",)
        widgets = {
            'email': forms.EmailInput(
                attrs={'class': 'subscribe__input'})
        }
        error_messages = {
            'email': {
                'unique': _('This email is already subscribed')
            }
        }

core/views.py
from django.core.paginator import Paginator
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.views.generic import *
from base_user.tools.login_helper_view import AccountCompleteRequired
from core.forms import *
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse
from django.contrib.auth.mixins import UserPassesTestMixin
from datetime import date


# Create your views here.

class BaseIndexView(TemplateView):
    template_name = 'home/index.html'

    def get(self, request, *args, **kwargs):
        if self.request.user.is_authenticated:
            return redirect(reverse_lazy('account:account-detail', kwargs={'slug': self.request.user.slug}))
        else:
            return super().get(request)


class WishCreateView(AccountCompleteRequired, LoginRequiredMixin, UserPassesTestMixin, CreateView):
    form_class = WishCreationForm
    template_name = 'wish/create.html'
    event_type_model = EventType

    def test_func(self):
        date_of_birth = self.request.user.date_of_birth
        today = date.today()
        day = date_of_birth.day
        month = date_of_birth.month
        if month == 2 and day == 29:
            day = 28

        birthday = date(today.year, month, day)
        days_until_birthday = (birthday - today).days
        if 60 > days_until_birthday > 0:
            return True

    def form_valid(self, form):
        action = self.request.POST.get('publish', None)
        files = self.request.FILES.getlist('multi_image', None)
        wish = form.save(commit=False)
        wish.user = self.request.user
        birthday_event = self.event_type_model.objects.get(title=0)
        wish.event_type = birthday_event
        wish.deadline = self.request.user.date_of_birth
        if action == 'publish':
            wish.published = True
        wish.save()
        if files:
            for f in files:
                Image.objects.create(url=f, wish=wish)
        return super().form_valid(form)

    def get_initial(self):
        self.initial.update(
            {'name': self.request.user.first_name,
             'surname': self.request.user.last_name}
        )
        return super(WishCreateView, self).get_initial()

    def get_success_url(self):
        return reverse_lazy('account:account-detail', kwargs={'slug': self.request.user.slug})

    def form_invalid(self, form):
        print(form.errors)
        return super().form_invalid(form)


class WishesListView(AccountCompleteRequired, LoginRequiredMixin, ListView):
    model = Wish
    template_name = 'wish/wishes.html'
    context_object_name = 'wishes'
    paginate_by = 8

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        data = self.get_queryset()
        context['wishes_count'] = self.get_queryset().count()
        page = self.request.GET.get('page', 1) if self.request.GET.get('page', 1) != '' else 1
        paginator = Paginator(data, self.paginate_by)
        return context

    def get_queryset(self):
        qs = super().get_queryset()
        qs = qs.filter(published=True, is_deleted=False)
        return qs


class WishUpdateView(AccountCompleteRequired, LoginRequiredMixin, UpdateView):
    model = Wish
    template_name = 'wish/update.html'
    form_class = WishCreationForm

    def form_valid(self, form):
        action = self.request.POST.get('publish', None)
        if action == 'publish':
            self.object.published = True
        files = self.request.FILES.getlist('multi_image')
        for f in files:
            Image.objects.create(url=f, wish=self.object)
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('account:account-detail', kwargs={'slug': self.object.user.slug})


class WishDetailView(DetailView):
    model = Wish
    template_name = 'wish/detail.html'
    context_object_name = 'wish'


class WishAjaxView(View):
    ajax_template = 'partials/wishes.html'

    def get(self, request, *args, **kwargs):
        if request.is_ajax():
            page = request.GET.get('page', False)
            if page:
                wish_list = Wish.objects.filter(published=True, is_deleted=False)
                paginator = Paginator(wish_list, 8)
                wishes = paginator.get_page(page)
            else:
                wishes = {}
            return render(request, self.ajax_template, {'wishes': wishes, 'has_next': wishes.has_next()})
        else:
            return JsonResponse({
                "error": "Method not allowed"
            }, status=405)


class WishDeleteView(View):

    def get(self, request, *args, **kwargs):
        if request.is_ajax():
            slug = request.GET.get('slug', False)
            print(slug)
            if slug:
                wish = Wish.objects.get(slug=slug)
                wish.is_deleted = True
                wish.save()
                return HttpResponse(status=200)
        else:
            return JsonResponse({
                "error": "Method not allowed"
            }, status=405)


class ComingSoonView(TemplateView):
    template_name = 'additional/coming-soon.html'


class PrivacyPolicyView(ListView):
    model = PrivacyPolicy
    template_name = 'additional/privacy-policy.html'
    context_object_name = 'privacy_policy'


class SubscribeView(CreateView):
    form_class = SubscribeForm
    success_url = reverse_lazy('core:base-index')

    def get(self, request, *args, **kwargs):
        return redirect(self.success_url)

    def form_valid(self, form):
        if self.request.is_ajax():
            subscribe = form.save()
            subscribe.reference_url = self.request.POST.get("reference_url")
            subscribe.save()
            return JsonResponse({
                "save": True
            })

    def form_invalid(self, form):
        return JsonResponse({
            "save": False,
            "message": form.errors
        })


class HowItWorksView(TemplateView):
    template_name = 'additional/howitworks.html'

core/templates/wish/create.html
{% extends 'base/index.html' %}
{% load static widget_tweaks i18n %}
{% block content %}
    <div class="mt-8 mb-12">
        <h1 class="page-header text-center mb-11">{% trans 'Arzu yarat' %}</h1>
        <div class="row">
            <div class="col-lg-8">
                <form class="row" method="post" id="create-wish" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="col-12 col-sm-5 p-2">
                        <label class="create__input-label" for="person-photo">{% trans 'Şəkil' %}</label>
                    </div>
                    <div class="col-12 col-sm-7 mb-6 mb-sm-11">
                        <div id="person-photo-btn" class="create__profile-photo"><span>+</span></div>
                        {{ form.image }}
                    </div>
                    <div class="col-12 col-sm-5 p-2">
                        <label class="create__input-label" for="person-name">{% trans 'Ad' %}</label>
                    </div>
                    <div class="col-12 col-sm-7 mb-6 mb-sm-11">
                        {{ form.name }}
                    </div>
                    <div class="col-12 col-sm-5 p-2">
                        <label class="create__input-label" for="person-surname">{% trans 'Soyad' %}</label>
                    </div>
                    <div class="col-12 col-sm-7 mb-6 mb-sm-11">
                        {{ form.surname }}
                    </div>
                    <div class="col-12 col-sm-5 p-2">
                        <label class="create__input-label" for="event-name">{% trans 'Tədbirin adı' %}</label>
                    </div>
                    <div class="col-12 col-sm-7 mb-6 mb-sm-11">
                        {{ form.title }}
                    </div>
                    <div class="col-12 col-sm-5 p-2">
                        <label class="create__input-label" for="event-desc">{% trans 'Tədbirin qısa təsviri' %}</label>
                    </div>
                    <div class="col-12 col-sm-7 mb-6 mb-sm-11">
                        {{ form.description }}
                    </div>
                    <div class="col-12 col-sm-5 p-2">
                        <label class="create__input-label" for="required-amount">{% trans 'Lazım olan məbləğ' %}</label>
                    </div>
                    <div class="col-12 col-sm-7 mb-6 mb-sm-11">
                        <div class="row m-0 align-items-baseline flex-nowrap">
                            {{ form.required_amount }}
                            {% for radio in form.currency %}
                                {% if forloop.first %}
                                    <label for="{{ radio.id_for_label }}" class="p-0 mr-4">
                                        {{ radio.tag }}
                                        <span class="create__currency-manat">{{ radio.choice_label }}</span>
                                    </label>
                                {% else %}
                                    <label for="{{ radio.id_for_label }}" class="p-0">
                                        {{ radio.tag }}
                                        <span class="create__currency-usd">{{ radio.choice_label }}</span>
                                    </label>
                                {% endif %}
                            {% endfor %}
                        </div>
                    </div>
                    <div class="col-12 col-sm-5 p-2">
                        <label class="create__input-label" for="event-photo">{% trans 'Şəkil yüklə' %}</label>
                    </div>
                    <div class="col-12 col-sm-7 mb-6 mb-sm-11">
                        <div class="col-7 p-0">
                            <button class="button button--loader w-100 d-flex align-items-center justify-content-center"
                                    id="event-photo-btn">
                                <span class="mr-4">{% trans 'yüklə' %}</span>
                                <i class="fa fa-arrow-up create__btn-icon"></i>
                            </button>
                            {{ form.multi_image }}
                            <span class="terms" id="selected_img_count"></span>
                        </div>
                    </div>
                    <div class="col-12 col-sm-5 p-2">
                        <label class="create__input-label" for="identification-card-input">{% trans 'Şəxsiyyət vəsiqəsini yüklə' %}</label>
                    </div>
                    <div class="col-12 col-sm-7 mb-6 mb-sm-11">
                        <div class="col-7 p-0">
                            <button class="button button--loader w-100 d-flex align-items-center justify-content-center"
                                    id="identification-card-btn">
                                <span class="mr-4">{% trans 'yüklə' %}</span>
                                <i class="fa fa-arrow-up create__btn-icon"></i>
                            </button>
                            {{ form.identification_card_image }}
                            <span class="terms" id="identification_card_img_count"></span>
                            <span class="error-text" id="file-error-text"></span>
                        </div>
                    </div>
                    <div class="col-12 col-sm-5 p-2">
                        <label class="create__input-label" for="event-video">{% trans 'Video yüklə' %}</label>
                    </div>
                    <div class="col-12 col-sm-7 mb-6 mb-sm-11">
                        {{ form.video }}
                    </div>
                    <div class="col-12 col-sm-5 p-2">
                        <label class="create__input-label" for="event-video">{% trans 'Arzu üçün qısa url' %}</label>
                    </div>
                    <div class="col-12 col-sm-7 mb-6 mb-sm-11">
                        {{ form.slug }}
                        {% if form.slug.errors %}
                            <div class="alert alert-danger col text-center slug_error_message" role="alert">
                                {% for error in form.slug.errors %}{{ error }}{% endfor %}
                            </div>
                        {% endif %}
                    </div>

                    <div class="col-12 mb-7">
                        <label class="d-flex align-items-center">
                            <input type="checkbox" id="check_" class="option-input checkbox mr-2" name="terms-and-conditions"/>
                            <span class="terms"><a href="#" class="">{% trans 'Qaydalarla' %}</a> {% trans 'tanış oldum və razıyam' %}</span>
                        </label>
                    </div>
                    <div class="col-12">
                        <button name="publish" value="publish" type="submit" class="button button--primary mr-7 mb-6 mb-sm-0">{% trans 'Paylaş' %}</button>
                        <button name="save" value="save" type="submit" class="button button--secondary">{% trans 'Yadda saxla' %}</button>
                    </div>
                </form>
            </div>
            <div class="col-lg-4 p-10 p-lg-0 mt-6">
                <picture>
                    <source media="(min-width: 600px)" srcset="{% static 'wishx/assets/arzuyaratsehife@2x.png' %}">
                    <img src="{% static 'wishx/assets/arzuyaratsehife.png' %}" alt="qeydiyyat" class="w-100">
                </picture>
            </div>
        </div>
    </div>
{% endblock content %}

core/templates/wish/update.html
{% extends 'base/index.html' %}
{% load static widget_tweaks i18n %}
{% block content %}
    <div class="mt-8 mb-12">
        <h1 class="page-header text-center mb-11">{% trans 'Arzuda dəyişiklik et' %}</h1>
        <div class="row">
            <div class="col-lg-8">
                <form class="row" method="post" id="create-wish" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="col-12 col-sm-5 p-2">
                        <label class="create__input-label" for="person-photo">{% trans 'Şəkil' %}</label>
                    </div>
                    <div class="col-12 col-sm-7 mb-6 mb-sm-11">
                        <div id="person-photo-btn" class="create__profile-photo"><span>+</span>
                        {% if object.image %}
                            <img id="profile_img" class="card__image" src="{{ object.image.url }}" alt="profile photo">
                        {% else %}
                            <img id="profile_img" class="card__image" src="{% static 'wishx/assets/default_user.png' %}" alt="profile photo">
                        {% endif %}
                        </div>
                        {{ form.image }}
                    </div>
                    <div class="col-12 col-sm-5 p-2">
                        <label class="create__input-label" for="person-name">{% trans 'Ad' %}</label>
                    </div>
                    <div class="col-12 col-sm-7 mb-6 mb-sm-11">
                        {{ form.name }}
                    </div>
                    <div class="col-12 col-sm-5 p-2">
                        <label class="create__input-label" for="person-surname">{% trans 'Soyad' %}</label>
                    </div>
                    <div class="col-12 col-sm-7 mb-6 mb-sm-11">
                        {{ form.surname }}
                    </div>
                    <div class="col-12 col-sm-5 p-2">
                        <label class="create__input-label" for="event-name">{% trans 'Tədbirin adı' %}</label>
                    </div>
                    <div class="col-12 col-sm-7 mb-6 mb-sm-11">
                        {{ form.title }}
                    </div>
                    <div class="col-12 col-sm-5 p-2">
                        <label class="create__input-label" for="event-desc">{% trans 'Tədbirin qısa təsviri' %}</label>
                    </div>
                    <div class="col-12 col-sm-7 mb-6 mb-sm-11">
                        {{ form.description }}
                    </div>
                    <div class="col-12 col-sm-5 p-2">
                        <label class="create__input-label" for="required-amount">{% trans 'Lazım olan məbləğ' %}</label>
                    </div>
                    <div class="col-12 col-sm-7 mb-6 mb-sm-11">
                        <div class="row m-0 align-items-baseline flex-nowrap">
                            {{ form.required_amount }}
                            {% for radio in form.currency %}
                                {% if forloop.first %}
                                    <label for="{{ radio.id_for_label }}" class="p-0 mr-4">
                                        {{ radio.tag }}
                                        <span class="create__currency-manat">{{ radio.choice_label }}</span>
                                    </label>
                                {% else %}
                                    <label for="{{ radio.id_for_label }}" class="p-0">
                                        {{ radio.tag }}
                                        <span class="create__currency-usd">{{ radio.choice_label }}</span>
                                    </label>
                                {% endif %}
                            {% endfor %}
                        </div>
                    </div>
                    <div class="col-12 col-sm-5 p-2">
                        <label class="create__input-label" for="event-photo">{% trans 'Şəkil yüklə' %}</label>
                    </div>
                    <div class="col-12 col-sm-7 mb-6 mb-sm-11">
                        <div class="col-7 p-0">
                            <button class="button button--loader w-100 d-flex align-items-center justify-content-center"
                                    id="event-photo-btn">
                                <span class="mr-4">{% trans 'yüklə' %}</span>
                                <i class="fa fa-arrow-up create__btn-icon"></i>
                            </button>
                            {{ form.multi_image }}
                            <span class="terms" id="selected_img_count"></span>
                        </div>
                    </div>
                    <div class="col-12 col-sm-5 p-2">
                        <label class="create__input-label" for="event-video">{% trans 'Video yüklə' %}</label>
                    </div>
                    <div class="col-12 col-sm-7 mb-6 mb-sm-11">
                        {{ form.video }}
                    </div>
                    <div class="col-12 col-sm-5 p-2">
                        <label class="create__input-label" for="event-video">{% trans 'Arzu üçün qısa url' %}</label>
                    </div>
                    <div class="col-12 col-sm-7 mb-6 mb-sm-11">
                        {{ form.slug }}
                        {% if form.slug.errors %}
                            <div class="alert alert-danger col text-center slug_error_message" role="alert">
                                {% for error in form.slug.errors %}{{ error }}{% endfor %}
                            </div>
                        {% endif %}
                    </div>

                    <div class="col-12">
                        {% if not object.published %}
                            <button name="publish" value="publish" type="submit" class="button button--primary mr-7 mb-6 mb-sm-0">{% trans 'Paylaş' %}</button>
                        {% endif %}
                        <button name="save" value="save" type="submit" class="button button--secondary">{% trans 'Yadda saxla' %}</button>
                    </div>
                </form>
            </div>
            <div class="col-lg-4 p-10 p-lg-0 mt-6">
                <picture>
                    <source media="(min-width: 600px)" srcset="{% static 'wishx/assets/arzuyaratsehife@2x.png' %}">
                    <img src="{% static 'wishx/assets/arzuyaratsehife.png' %}" alt="qeydiyyat" class="w-100">
                </picture>
            </div>
        </div>
    </div>
{% endblock content %}

core/templates/wish/wishes.html
{% extends 'base/index.html' %}
{% load static widget_tweaks i18n %}

{% block content %}
    <div class="mt-8 mb-12 text-center">
            <h1 class="page-header">{% trans 'Tədbirlər' %}</h1>
            <div id="wishes-container" class="row">
                {% for wish in wishes %}
                    <div class="col-12 col-sm-6 col-lg-4 col-xl-3 wish-list-card">
                        <div class="events-card events-card--all">
                        <div class="card__image-wrapper card__image-wrapper--events">
                            <img class="card__image" src="{{ wish.get_cover }}" alt="event photo">
                        </div>
                        <div class="card__image-wrapper card__image-wrapper--user">
                            {% if wish.image %}
                                <img class="card__image" src="{{ wish.image.url }}" alt="user photo">
                            {% elif wish.user.profile_picture %}
                                <img class="card__image" src="{{ wish.user.get_profile_picture }}" alt="user photo">
                            {% else %}
                                <img class="card__image" src="{% static 'wishx/assets/default_user.png' %}" alt="user photo">
                            {% endif %}
                        </div>
                        <p class="events-card__user-name">{{ wish.name }} {{ wish.surname }}</p>
                        <p class="events-card__event-name mb-5"><a href="{{ wish.get_absolute_url }}">{{ wish.title }}</a></p>
                        <div class="event-info event-info--events-card mb-4">
                            <div>
                                <p class="event-info__header">{% trans 'Lazım olan məbləğ' %}</p>
                                <p class="event-info__data">{{ wish.required_amount }} {{ wish.currency }}</p>
                            </div>
                            <div>
                                <p class="event-info__header">{% trans 'Toplanan məbləğ' %}</p>
                                <p class="event-info__data">{{ wish.accumulated_amount }} {{ wish.currency }}</p>
                            </div>
                        </div>
                    </div>
                    </div>
                {% endfor %}
            </div>
            {% if is_paginated %}
                {% if page_obj.has_next %}
                    <button data-id="1" id="load_more" class="button button--secondary">{% trans 'Daha çox' %}</button>
                {% endif %}
            {% endif %}
            <input id="request-url" type="hidden" value="{% url 'core:wishes-ajax' %}">
            <input id="current-url" type="hidden" value="{% url 'core:wishes' %}">
            <input id="all_wishes_count" type="hidden" value="{{ wishes_count }}">
        </div>
{% endblock content %}